# Image tag must match system hardware. https://github.com/dizcza/docker-hashcat#tags
FROM dizcza/docker-hashcat:cuda

ARG ROOT_PASSWORD
RUN echo root:${ROOT_PASSWORD} | chpasswd

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y openssh-server
RUN mkdir /var/run/sshd

#RUN apt -y install kali-linux-headless

RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

EXPOSE 22
CMD [ "/usr/sbin/sshd", "-D" ]